import { fetchData } from ".";

export async function create(
  accessToken: string = "eyJhbGciOiJIUzI1NiIsImtpZCI6InAzVktKVzhiY2tJdTZKNysiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE0MzM0NjE2LCJpYXQiOjE3MTM3Mjk4MTYsImlzcyI6Imh0dHBzOi8vdXh6ZGFoYnFramhzc2FocWV6cnouc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjE4ZGVhMjlmLTk4ZDItNGIxMS05ZDRjLTExZDgwYzIxNGJlYSIsImVtYWlsIjoiaWNhcm9wYWl2YWRiekBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImlzX3N0YWZmIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcxMzcyOTgxNn1dLCJzZXNzaW9uX2lkIjoiMmFmZjdjNTctODRkNi00ODA2LWFiYjQtMTFkZGZlOWU1NjEzIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.rtZYNx7riZwhuN4AdFVIlupd6Kfrcv65HSLYQIuMtjY",
  path: string,
  body: object
) {
   await fetchData(accessToken).post(path, body);
}
