import { fetchData } from ".";

export async function findAll(
  accessToken: string = "eyJhbGciOiJIUzI1NiIsImtpZCI6InAzVktKVzhiY2tJdTZKNysiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyNjI0OTA5LCJpYXQiOjE3MTIwMjAxMDksImlzcyI6Imh0dHBzOi8vdXh6ZGFoYnFramhzc2FocWV6cnouc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjE4ZGVhMjlmLTk4ZDItNGIxMS05ZDRjLTExZDgwYzIxNGJlYSIsImVtYWlsIjoiaWNhcm9wYWl2YWRiekBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImlzX3N0YWZmIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcxMjAyMDEwOX1dLCJzZXNzaW9uX2lkIjoiZGQ0MjQ3YzMtMzkwNS00MjQ0LWFkZGEtY2RiZGE0NTkzNzg0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.1ggB3G7ISzHLRAAA-SXnZm4h-SVD-fzfhEstFFB7RVA",
  path: string,
  params?: object
) {
  const { data } = await fetchData(accessToken).get(path, {
    params,
  });
  return data;
}
